-- Add up migration script here
ALTER TABLE media ADD COLUMN longitude DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE media ADD COLUMN latitude DOUBLE PRECISION DEFAULT NULL;

ALTER TABLE media ADD COLUMN metadata_version INT NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN thumbnail_version INT NOT NULL DEFAULT 0;

