-- Add up migration script here
ALTER TABLE media ADD COLUMN longitude DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE media ADD COLUMN latitude DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE media ADD COLUMN is_screenshot BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE media ADD COLUMN import_id INTEGER DEFAULT -1;

ALTER TABLE media ADD COLUMN format TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE media ADD COLUMN metadata_version INT NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN thumbnail_version INT NOT NULL DEFAULT 0;

INSERT INTO kv (key, value, created_at, updated_at) VALUES ('last_import_id', '-1', CURRENT_DATE, CURRENT_DATE);

